# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - Rscript -e 'install.packages(c("dplyr", "ggplot2", "readr", "grid", "lubridate", "leaflet", "scales"))'
